# Generated by Django 4.0.2 on 2022-02-28 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectionApp', '0002_section_section_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=1, unique=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sectionApp.section')),
            ],
        ),
    ]
