# Generated by Django 4.0.2 on 2022-02-28 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectionApp', '0002_section_section_head'),
        ('classApp', '0002_class_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sectionApp.section'),
        ),
    ]
