# Generated by Django 4.0.2 on 2022-02-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0003_alter_class_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=1),
        ),
    ]
