# Generated by Django 4.0.2 on 2022-02-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(unique=True)),
            ],
        ),
    ]
