# Generated by Django 4.0.2 on 2022-02-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectApp', '0001_initial'),
        ('sectionApp', '0002_section_section_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='subject',
            field=models.ManyToManyField(to='subjectApp.Subject'),
        ),
    ]
